import 'dart:math';

class RandomCities{
  String getCityNames(){
    var cityNames = [
      "Lahore",
      "Karachi",
      "Islamabad",
      "Rawalpindi",
      "London",
      "Mumbai",
      "Delhi",
      "Swat",
      "Paris",
      "New York City",
      "London",
      "England",
      "Bangkok",
      "Thailand",
      "Hong Kong",
      "China",
      "Dubai",
      "United Arab Emirates",
      "Singapore",
      "Rome",
      "Italy",
      "Macau",
      "China",
      "Istanbul",
      "Turkey",
      "Kuala Lumpur",
      "Malaysia",
      "Delhi",
      "India",
      "Tokyo",
      "Japan",
      "Antalya",
      "Turkey",
      "Mexico City",
      "Mexico",
      "Porto",
      "Portugal",
      "San Francisco",
      "USA",
      "Beijing",
      "China",
      "Los Angeles",
      "USA",
      "Chicago",
      "USA",
      "Barcelona",
      "Spain",
      "Abu Dhabi",
      "United Arab Emirates",
      "Amsterdam",
      "Netherlands",
      "Madrid",
      "Spain",
      "Sydney",
      "Australia",
      "Mexico",
      "Lisbon",
      "Portugal",
      "Vienna",
      "Austria",
    ];
    final random = Random();
    var city = cityNames[random.nextInt(cityNames.length)];
    return city;
  }

}